/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica2.views;

import javax.swing.*;
import practica2.views.PersonajeModel;

/**
 *
 * @author Miguer Corado
 */
public class VistaJugar extends javax.swing.JFrame {
    
    private PersonajeModel jugador;
    private PersonajeModel oponente;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaJugar.class.getName());
  
    /**
     * Creates new form VistaJugar
     */
    public VistaJugar() {
    initComponents();
}

    public void iniciarCarrera(PersonajeModel jugador, PersonajeModel oponente) {
        this.jugador = jugador;
        this.oponente = oponente;
  
        // Mostrar nombres en los labels
        lblJugador.setText("J: " + jugador.getNombre());
        lblOponente.setText("O: " + oponente.getNombre());
        
        // Inicializar posiciones de los magos en los labels
        lblMago1.setLocation(0, lblMago1.getY());
        lblMago2.setLocation(0, lblMago2.getY());

        // Aquí se podrían inicializar posiciones, puntos y demás
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        lblMago1 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lblMago2 = new javax.swing.JLabel();
        lblJugador = new javax.swing.JLabel();
        lblOponente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegresar.setText("SALIR");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        lblMago1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblMago1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMago1.setText("O");

        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);

        lblMago2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblMago2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMago2.setText("[ ]");

        lblJugador.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugador.setText("J");

        lblOponente.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblOponente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOponente.setText("O");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOponente, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblMago2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblMago1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnIniciar)
                        .addGap(42, 42, 42)
                        .addComponent(btnRegresar)))
                .addGap(27, 214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMago1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblOponente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMago2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(btnRegresar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
    
    // Hilo para mago 1 (jugador)
        Thread hiloMago1 = new Thread(() -> {
            for (int x = lblMago1.getX(); x <= this.getWidth() - lblMago1.getWidth(); x += 10) {
                final int nuevaX = x;
                javax.swing.SwingUtilities.invokeLater(() -> {
                    lblMago1.setLocation(nuevaX, lblMago1.getY());
                });
                try {
                    Thread.sleep(jugador.getEscoba().getDormirSeg());
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        hiloMago1.start();

        // Hilo para mago 2 (oponente)
        Thread hiloMago2 = new Thread(() -> {
            for (int x = lblMago2.getX(); x <= this.getWidth() - lblMago2.getWidth(); x += 10) {
                final int nuevaX = x;
                javax.swing.SwingUtilities.invokeLater(() -> {
                    lblMago2.setLocation(nuevaX, lblMago2.getY());
                });
                try {
                    Thread.sleep(oponente.getEscoba().getDormirSeg());
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        hiloMago2.start();


    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaJugar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblMago1;
    private javax.swing.JLabel lblMago2;
    private javax.swing.JLabel lblOponente;
    // End of variables declaration//GEN-END:variables
}